### ISSUE TITLE
Update the `README.md` according to the website's `How-to` content

### ISSUE THREAD

**Issue by Garvit1809** [zeborg/Auto-MERGE-Project#11]
Is there an issue in this repo that I can work on??

**Comment by zeborg** [comment]
Yes, @Garvit1809. If you're okay with this suggestion, would you like to work on the `README.md` file of this repo to help new contributors get familiar with the steps to contribute to this repo?

**Comment by zeborg** [comment]
Yes, you may refer to the content that's present in the `How-to` section of the [website](https://automergekrmu.herokuapp.com/) and convert it to markdown for adding it to `README.md`. Screenshot shared below for reference:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/37282098/193975373-fdea3a3f-2b87-464c-ae32-54c2ea705fbd.png">

Also, if you haven't added yourself as a contributor to the repo yet, feel free to go through the steps and add yourself too 🙂

**Comment by Garvit1809** [comment]
Okay, will update soon :)

**Comment by Garvit1809** [comment]
In my vscode, the color text is showing but it not in the github readme
In VsCode 👇
![Readme1](https://user-images.githubusercontent.com/89806031/193987567-d87c7cbe-6e05-46fb-b5c1-c2f225fb0ca4.png)

In Github Readme 👇
![Readme2](https://user-images.githubusercontent.com/89806031/193987682-1171ab73-b6bc-4561-9fae-d8c04098b1c1.png)

Is there any other way to do that or should I italicize that part of text

**Comment by zeborg** [comment]
You can enclose the colored names within single backticks, that is, ``
Also, please make sure to remove the dot before my username in the example at point no. 3.

**Comment by Garvit1809** [comment]
It seems we cant add colorful text in Github Readme, so I have made the changes accordingly.
Also should I add a section for a hacktoberfest section, that this repo is under hacktoberfest  @zeborg ??

**Comment by zeborg** [comment]
@Garvit1809 - This PR got automerged by the bot, but it would be a good idea to add a section for hacktoberfest. You can create a new PR for this change, and if you could also update the `README.md` to also mention the deployed website's link, that would be great.

**Comment by Garvit1809** [comment]
Sorry I didn't saw this message, will make a PR soon
